services:
  core:
    container_name: warroom-core
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
